### ISSUE TITLE
Build Issue for Mac

### ISSUE THREAD

**Issue by Liwink** [kallewoof/btcdeb#29] opened 2019-03-12 22:30 UTC
What I have done:

```terminal
$ xcode-select --install
$ brew install libtool autoconf
$ GCC --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 10.0.0 (clang-1000.10.44.4)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
$ ./autogen.sh
```
Issue:

```terminal
$ ./configure 
checking build system type... x86_64-apple-darwin18.2.0
checking host system type... x86_64-apple-darwin18.2.0
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... build-aux/install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether to enable maintainer-specific portions of Makefiles... yes
checking whether make supports nested variables... (cached) yes
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... configure: error: in `/Users/xxx/btcdeb':
configure: error: cannot run C++ compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details
```

```
$ cat config.log
This file contains any messages produced by compilers while
running configure, to aid debugging if configure makes a mistake.

It was created by Bitcoin Debugger configure 0.16.99, which was
generated by GNU Autoconf 2.69.  Invocation command line was

  $ ./configure 

## --------- ##
## Platform. ##
## --------- ##

hostname = xuxinyudeMBP.lan1
uname -m = x86_64
uname -r = 18.2.0
uname -s = Darwin
uname -v = Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64

/usr/bin/uname -p = i386
/bin/uname -X     = unknown

/bin/arch              = unknown
/usr/bin/arch -k       = unknown
/usr/convex/getsysinfo = unknown
/usr/bin/hostinfo      = Mach kernel version:
	 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64
Kernel configured for up to 4 processors.
2 processors are physically available.
4 processors are logically available.
Processor type: x86_64h (Intel x86-64h Haswell)
Processors active: 0 1 2 3
Primary memory available: 8.00 gigabytes
Default processor set: 368 tasks, 1437 threads, 4 processors
Load average: 1.31, Mach factor: 2.68
/bin/machine           = unknown
/usr/bin/oslevel       = unknown
/bin/universe          = unknown

PATH: /Library/Frameworks/Python.framework/Versions/3.6/bin
PATH: /Users/xuxinyu/anaconda3/bin
PATH: /Library/Frameworks/Python.framework/Versions/3.7/bin
PATH: /Library/Frameworks/Python.framework/Versions/3.6/bin
PATH: /Library/Frameworks/Python.framework/Versions/3.7/bin
PATH: /Library/Frameworks/Python.framework/Versions/3.7/bin
PATH: /Library/Frameworks/Python.framework/Versions/2.7/bin
PATH: /Users/xuxinyu/anaconda3/bin
PATH: /Library/Frameworks/Python.framework/Versions/3.7/bin
PATH: /Library/Frameworks/Python.framework/Versions/2.7/bin
PATH: /usr/local/bin
PATH: /usr/bin
PATH: /bin
PATH: /usr/sbin
PATH: /sbin
PATH: /Library/TeX/texbin
PATH: /usr/local/MacGPG2/bin
PATH: /usr/local/share/dotnet
PATH: ~/.dotnet/tools
PATH: /Library/Frameworks/Mono.framework/Versions/Current/Commands


## ----------- ##
## Core tests. ##
## ----------- ##

configure:2687: checking build system type
configure:2701: result: x86_64-apple-darwin18.2.0
configure:2721: checking host system type
configure:2734: result: x86_64-apple-darwin18.2.0
configure:2777: checking for a BSD-compatible install
configure:2845: result: /usr/bin/install -c
configure:2856: checking whether build environment is sane
configure:2911: result: yes
configure:3062: checking for a thread-safe mkdir -p
configure:3101: result: build-aux/install-sh -c -d
configure:3108: checking for gawk
configure:3138: result: no
configure:3108: checking for mawk
configure:3138: result: no
configure:3108: checking for nawk
configure:3138: result: no
configure:3108: checking for awk
configure:3124: found /usr/bin/awk
configure:3135: result: awk
configure:3146: checking whether make sets $(MAKE)
configure:3168: result: yes
configure:3197: checking whether make supports nested variables
configure:3214: result: yes
configure:3333: checking whether to enable maintainer-specific portions of Makefiles
configure:3342: result: yes
configure:3367: checking whether make supports nested variables
configure:3384: result: yes
configure:3513: checking for C++ compiler version
configure:3522: x86_64-apple-darwin13.4.0-clang++ --version >&5
clang version 4.0.1 (tags/RELEASE_401/final)
Target: x86_64-apple-darwin13.4.0
Thread model: posix
InstalledDir: /Users/xuxinyu/anaconda3/bin
configure:3533: $? = 0
configure:3522: x86_64-apple-darwin13.4.0-clang++ -v >&5
clang version 4.0.1 (tags/RELEASE_401/final)
Target: x86_64-apple-darwin13.4.0
Thread model: posix
InstalledDir: /Users/xuxinyu/anaconda3/bin
configure:3533: $? = 0
configure:3522: x86_64-apple-darwin13.4.0-clang++ -V >&5
clang-4.0: error: argument to '-V' is missing (expected 1 value)
clang-4.0: error: no input files
configure:3533: $? = 1
configure:3522: x86_64-apple-darwin13.4.0-clang++ -qversion >&5
clang-4.0: error: unknown argument: '-qversion'
clang-4.0: error: no input files
configure:3533: $? = 1
configure:3553: checking whether the C++ compiler works
configure:3575: x86_64-apple-darwin13.4.0-clang++ -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -stdlib=libc++ -fvisibility-inlines-hidden -std=c++14 -fmessage-length=0 -D_FORTIFY_SOURCE=2 -mmacosx-version-min=10.9 -Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs conftest.cpp  >&5
ld: warning: ignoring file /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd, file was built for unsupported file format ( 0x2D 0x2D 0x2D 0x20 0x21 0x74 0x61 0x70 0x69 0x2D 0x74 0x62 0x64 0x2D 0x76 0x33 ) which is not the architecture being linked (x86_64): /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd
configure:3579: $? = 0
configure:3627: result: yes
configure:3630: checking for C++ compiler default output file name
configure:3632: result: a.out
configure:3638: checking for suffix of executables
configure:3645: x86_64-apple-darwin13.4.0-clang++ -o conftest -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -stdlib=libc++ -fvisibility-inlines-hidden -std=c++14 -fmessage-length=0 -D_FORTIFY_SOURCE=2 -mmacosx-version-min=10.9 -Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs conftest.cpp  >&5
ld: warning: ignoring file /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd, file was built for unsupported file format ( 0x2D 0x2D 0x2D 0x20 0x21 0x74 0x61 0x70 0x69 0x2D 0x74 0x62 0x64 0x2D 0x76 0x33 ) which is not the architecture being linked (x86_64): /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd
configure:3649: $? = 0
configure:3671: result: 
configure:3693: checking whether we are cross compiling
configure:3701: x86_64-apple-darwin13.4.0-clang++ -o conftest -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -stdlib=libc++ -fvisibility-inlines-hidden -std=c++14 -fmessage-length=0 -D_FORTIFY_SOURCE=2 -mmacosx-version-min=10.9 -Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs conftest.cpp  >&5
ld: warning: ignoring file /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd, file was built for unsupported file format ( 0x2D 0x2D 0x2D 0x20 0x21 0x74 0x61 0x70 0x69 0x2D 0x74 0x62 0x64 0x2D 0x76 0x33 ) which is not the architecture being linked (x86_64): /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd
Undefined symbols for architecture x86_64:
  "_fclose", referenced from:
      _main in conftest-0ac0d1.o
  "_ferror", referenced from:
      _main in conftest-0ac0d1.o
  "_fopen", referenced from:
      _main in conftest-0ac0d1.o
ld: symbol(s) not found for architecture x86_64
clang-4.0: error: linker command failed with exit code 1 (use -v to see invocation)
configure:3705: $? = 1
configure:3712: ./conftest
./configure: line 3714: ./conftest: No such file or directory
configure:3716: $? = 127
configure:3723: error: in `/Users/xuxinyu/btcdeb':
configure:3725: error: cannot run C++ compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details

## ---------------- ##
## Cache variables. ##
## ---------------- ##

ac_cv_build=x86_64-apple-darwin18.2.0
ac_cv_env_ARFLAGS_set=
ac_cv_env_ARFLAGS_value=
ac_cv_env_CCC_set=
ac_cv_env_CCC_value=
ac_cv_env_CC_set=set
ac_cv_env_CC_value=x86_64-apple-darwin13.4.0-clang
ac_cv_env_CFLAGS_set=set
ac_cv_env_CFLAGS_value='-march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe'
ac_cv_env_CPPFLAGS_set=set
ac_cv_env_CPPFLAGS_value='-D_FORTIFY_SOURCE=2 -mmacosx-version-min=10.9'
ac_cv_env_CPP_set=
ac_cv_env_CPP_value=
ac_cv_env_CXXCPP_set=
ac_cv_env_CXXCPP_value=
ac_cv_env_CXXFLAGS_set=set
ac_cv_env_CXXFLAGS_value='-march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -stdlib=libc++ -fvisibility-inlines-hidden -std=c++14 -fmessage-length=0'
ac_cv_env_CXX_set=set
ac_cv_env_CXX_value=x86_64-apple-darwin13.4.0-clang++
ac_cv_env_LDFLAGS_set=set
ac_cv_env_LDFLAGS_value='-Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs'
ac_cv_env_LIBS_set=
ac_cv_env_LIBS_value=
ac_cv_env_LT_SYS_LIBRARY_PATH_set=
ac_cv_env_LT_SYS_LIBRARY_PATH_value=
ac_cv_env_OBJCXXFLAGS_set=
ac_cv_env_OBJCXXFLAGS_value=
ac_cv_env_OBJCXX_set=
ac_cv_env_OBJCXX_value=
ac_cv_env_PKG_CONFIG_LIBDIR_set=
ac_cv_env_PKG_CONFIG_LIBDIR_value=
ac_cv_env_PKG_CONFIG_PATH_set=
ac_cv_env_PKG_CONFIG_PATH_value=
ac_cv_env_PKG_CONFIG_set=
ac_cv_env_PKG_CONFIG_value=
ac_cv_env_PYTHONPATH_set=set
ac_cv_env_PYTHONPATH_value=/Library/Frameworks/Python.framework/Versions/3.6:
ac_cv_env_build_alias_set=
ac_cv_env_build_alias_value=
ac_cv_env_host_alias_set=
ac_cv_env_host_alias_value=
ac_cv_env_target_alias_set=
ac_cv_env_target_alias_value=
ac_cv_host=x86_64-apple-darwin18.2.0
ac_cv_path_install='/usr/bin/install -c'
ac_cv_prog_AWK=awk
ac_cv_prog_make_make_set=yes
am_cv_make_support_nested_variables=yes

## ----------------- ##
## Output variables. ##
## ----------------- ##

ACLOCAL='${SHELL} /Users/xuxinyu/btcdeb/build-aux/missing aclocal-1.16'
AMDEPBACKSLASH=''
AMDEP_FALSE=''
AMDEP_TRUE=''
AMTAR='$${TAR-tar}'
AM_BACKSLASH='\'
AM_DEFAULT_V='$(AM_DEFAULT_VERBOSITY)'
AM_DEFAULT_VERBOSITY='0'
AM_V='$(V)'
AR='/Users/xuxinyu/anaconda3/bin/x86_64-apple-darwin13.4.0-ar'
ARFLAGS='cr'
AUTOCONF='${SHELL} /Users/xuxinyu/btcdeb/build-aux/missing autoconf'
AUTOHEADER='${SHELL} /Users/xuxinyu/btcdeb/build-aux/missing autoheader'
AUTOMAKE='${SHELL} /Users/xuxinyu/btcdeb/build-aux/missing automake-1.16'
AWK='awk'
BITCOIN_CLI_NAME=''
BITCOIN_DAEMON_NAME=''
BITCOIN_GUI_NAME=''
BITCOIN_TX_NAME=''
BREW=''
BUILD_DARWIN_FALSE=''
BUILD_DARWIN_TRUE=''
CC='x86_64-apple-darwin13.4.0-clang'
CCACHE=''
CCDEPMODE=''
CFLAGS='-march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe'
CLIENT_VERSION_BUILD=''
CLIENT_VERSION_IS_RELEASE=''
CLIENT_VERSION_MAJOR=''
CLIENT_VERSION_MINOR=''
CLIENT_VERSION_REVISION=''
COPYRIGHT_HOLDERS=''
COPYRIGHT_HOLDERS_FINAL=''
COPYRIGHT_HOLDERS_SUBSTITUTION=''
COPYRIGHT_YEAR=''
CPP=''
CPPFILT=''
CPPFLAGS='-D_FORTIFY_SOURCE=2 -mmacosx-version-min=10.9'
CXX='x86_64-apple-darwin13.4.0-clang++'
CXXCPP=''
CXXDEPMODE=''
CXXFLAGS='-march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -stdlib=libc++ -fvisibility-inlines-hidden -std=c++14 -fmessage-length=0'
CYGPATH_W='echo'
DEFS=''
DEPDIR=''
DLLTOOL=''
DSYMUTIL=''
DUMPBIN=''
ECHO_C='\c'
ECHO_N=''
ECHO_T=''
EGREP=''
ENABLE_DANGEROUS_FALSE=''
ENABLE_DANGEROUS_TRUE=''
ENABLE_WALLET_FALSE=''
ENABLE_WALLET_TRUE=''
EXEEXT=''
FGREP=''
GCOV=''
GENHTML=''
GENISOIMAGE=''
GIT=''
GLIBC_BACK_COMPAT_FALSE=''
GLIBC_BACK_COMPAT_TRUE=''
GREP=''
HAVE_CXX11=''
HEXDUMP=''
IMAGEMAGICK_CONVERT=''
INSTALLNAMETOOL=''
INSTALL_DATA='${INSTALL} -m 644'
INSTALL_PROGRAM='${INSTALL}'
INSTALL_SCRIPT='${INSTALL}'
INSTALL_STRIP_PROGRAM='$(install_sh) -c -s'
LCOV=''
LD='/Users/xuxinyu/anaconda3/bin/x86_64-apple-darwin13.4.0-ld'
LDFLAGS='-Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs'
LIBOBJS=''
LIBS=''
LIBTOOL='/Users/xuxinyu/anaconda3/bin/x86_64-apple-darwin13.4.0-libtool'
LIBTOOL_APP_LDFLAGS=''
LIPO='/Users/xuxinyu/anaconda3/bin/x86_64-apple-darwin13.4.0-lipo'
LN_S=''
LTLIBOBJS=''
LT_SYS_LIBRARY_PATH=''
MAINT=''
MAINTAINER_MODE_FALSE='#'
MAINTAINER_MODE_TRUE=''
MAKEINFO='${SHELL} /Users/xuxinyu/btcdeb/build-aux/missing makeinfo'
MAKENSIS=''
MANIFEST_TOOL=''
MKDIR_P='build-aux/install-sh -c -d'
NM='/Users/xuxinyu/anaconda3/bin/x86_64-apple-darwin13.4.0-nm'
NMEDIT='/Users/xuxinyu/anaconda3/bin/x86_64-apple-darwin13.4.0-nmedit'
OBJCOPY=''
OBJCXX=''
OBJCXXDEPMODE=''
OBJCXXFLAGS=''
OBJDUMP=''
OBJEXT=''
OTOOL64=''
OTOOL='/Users/xuxinyu/anaconda3/bin/x86_64-apple-darwin13.4.0-otool'
PACKAGE='btcdeb'
PACKAGE_BUGREPORT='https://github.com/kallewoof/btcdeb/issues'
PACKAGE_NAME='Bitcoin Debugger'
PACKAGE_STRING='Bitcoin Debugger 0.16.99'
PACKAGE_TARNAME='btcdeb'
PACKAGE_URL='https://twitter.com/kallewoof'
PACKAGE_VERSION='0.16.99'
PATH_SEPARATOR=':'
PIC_FLAGS=''
PIE_FLAGS=''
PKG_CONFIG=''
PKG_CONFIG_LIBDIR=''
PKG_CONFIG_PATH=''
PORT=''
PTHREAD_CC=''
PTHREAD_CFLAGS=''
PTHREAD_LIBS=''
PYTHON=''
PYTHONPATH='/Library/Frameworks/Python.framework/Versions/3.6:'
RANLIB='/Users/xuxinyu/anaconda3/bin/x86_64-apple-darwin13.4.0-ranlib'
READELF=''
RELDFLAGS=''
RSVG_CONVERT=''
SED=''
SET_MAKE=''
SHELL='/bin/sh'
SSE42_CXXFLAGS=''
STRIP='/Users/xuxinyu/anaconda3/bin/x86_64-apple-darwin13.4.0-strip'
TARGET_DARWIN_FALSE=''
TARGET_DARWIN_TRUE=''
TARGET_WINDOWS_FALSE=''
TARGET_WINDOWS_TRUE=''
TIFFCP=''
VERSION='0.16.99'
WINDOWS_BITS=''
WINDRES=''
XGETTEXT=''
ac_ct_AR=''
ac_ct_CC=''
ac_ct_CXX=''
ac_ct_DUMPBIN=''
ac_ct_OBJCXX=''
am__EXEEXT_FALSE=''
am__EXEEXT_TRUE=''
am__fastdepCC_FALSE=''
am__fastdepCC_TRUE=''
am__fastdepCXX_FALSE=''
am__fastdepCXX_TRUE=''
am__fastdepOBJCXX_FALSE=''
am__fastdepOBJCXX_TRUE=''
am__include=''
am__isrc=''
am__leading_dot='.'
am__nodep=''
am__quote=''
am__tar='$${TAR-tar} chof - "$$tardir"'
am__untar='$${TAR-tar} xf -'
ax_pthread_config=''
bindir='${exec_prefix}/bin'
build='x86_64-apple-darwin18.2.0'
build_alias=''
build_cpu='x86_64'
build_os='darwin18.2.0'
build_vendor='apple'
datadir='${datarootdir}'
datarootdir='${prefix}/share'
docdir='${datarootdir}/doc/${PACKAGE_TARNAME}'
dvidir='${docdir}'
exec_prefix='NONE'
host='x86_64-apple-darwin18.2.0'
host_alias=''
host_cpu='x86_64'
host_os='darwin18.2.0'
host_vendor='apple'
htmldir='${docdir}'
includedir='${prefix}/include'
infodir='${datarootdir}/info'
install_sh='${SHELL} /Users/xuxinyu/btcdeb/build-aux/install-sh'
libdir='${exec_prefix}/lib'
libexecdir='${exec_prefix}/libexec'
localedir='${datarootdir}/locale'
localstatedir='${prefix}/var'
mandir='${datarootdir}/man'
mkdir_p='$(MKDIR_P)'
oldincludedir='/usr/include'
pdfdir='${docdir}'
prefix='NONE'
program_transform_name='s,x,x,'
psdir='${docdir}'
sbindir='${exec_prefix}/sbin'
sharedstatedir='${prefix}/com'
subdirs=''
sysconfdir='${prefix}/etc'
target_alias=''

## ----------- ##
## confdefs.h. ##
## ----------- ##

/* confdefs.h */
#define PACKAGE_NAME "Bitcoin Debugger"
#define PACKAGE_TARNAME "btcdeb"
#define PACKAGE_VERSION "0.16.99"
#define PACKAGE_STRING "Bitcoin Debugger 0.16.99"
#define PACKAGE_BUGREPORT "https://github.com/kallewoof/btcdeb/issues"
#define PACKAGE_URL "https://twitter.com/kallewoof"

configure: exit 1
```

Thanks!

**Comment by kallewoof** [comment] 2019-03-12 22:33
Weird. Can you show me what the config.log file says about the error?

**Comment by Liwink** [comment] 2019-03-12 22:35
Yes, I have updated. Thanks for replying!

**Comment by kallewoof** [comment] 2019-03-12 23:47
I looked around and it looks like this might be caused by not having Xcode installed, and only installing the tools. It's a big install, but could you try installing Xcode and trying again?

**Comment by Liwink** [comment] 2019-03-13 00:26
Thank you! Let me have a try.

**Comment by kallewoof** [comment] 2020-01-17 02:36
@Liwink Closing this -- please comment or open a new issue if the problem still persists.

**Closed by kallewoof** 2020-01-17 02:36 UTC
