### ISSUE TITLE
How to use exec command

### ISSUE THREAD

**Issue by JBaczuk** [kallewoof/btcdeb#21] opened 2018-08-06 17:57 UTC
Maybe this isn't implemented yet, or I'm doing it wrong, but I've tried:

```
btcdeb> exec OP_1
Error: Opcode missing or not understood
script  |  stack
--------+--------
btcdeb> exec 'OP_1'
Error: Opcode missing or not understood
script  |  stack
--------+--------
btcdeb> exec '[OP_1]'
error: invalid opcode [OP_1]
script  |  stack
--------+--------
btcdeb> exec 'OP_1 OP_2 OP_ADD'
error: invalid opcode OP_1 OP_2 OP_ADD
script  |  stack
--------+--------
btcdeb> exec 'OP_ADD'
Error: Opcode missing or not understood
script  |  stack
--------+--------
```

**Comment by kallewoof** [comment] 2018-08-06 22:17
Looks like a bug. Thanks for reporting, will look into it.

**Comment by kallewoof** [comment] 2018-08-07 03:49
The bug caused by this was fixed in latest master. Thanks again for the report!

**Closed** 2018-08-07 03:50 UTC
