### ISSUE TITLE
Segmentation fault in Ubuntu

### ISSUE THREAD

**Issue by the-beer-engineer** [kallewoof/btcdeb#10] opened 2018-04-25 10:46 UTC
I have installed btcdeb on an Ubuntu VM but am having trouble working with the program. Here is what I type/get:
$ btcdeb 0x515293
btcdeb -- type `btcdeb -h` for start up options
valid script
3 op script loaded. type `help` for usage information
script  |  stack
--------+--------
1       |
2       |
OP_ADD  |
#0001 1
btcdeb> step
Segmentation fault (core dumped)

Could I possibly be doing something wrong?

**Comment by the-beer-engineer** [comment] 2018-04-25 11:03
I installed libssl-dev and recompiled and now it works!
Thank you! Great utility :-)

**Comment by kallewoof** [comment] 2018-04-26 00:51
Huh! The build process should be more helpful there for sure. I'm gonna reopen this and see if I can make it more intelligent.

**Comment by kallewoof** [comment] 2018-05-16 12:30
I can't reproduce this problem on my side. Closing until someone else brings it up!

**Closed by kallewoof** 2018-05-16 12:30 UTC
